name: Run Unit Tests on Pull Requests

on:
  pull_request:
    branches:
      - "**"

obs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up permissions for Maven Wrapper
        run: chmod +x ./mvnw
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run Unit Tests
        run: ./mvnw test -Dtest=com.example.demo.CalculatorTest